/**
 * Lexicographic ordering keys for `binder_item.order_key`.
 *
 * A port of the server's `com.noveltea.order.FractionalIndex`, digit for digit. The
 * two must agree exactly: keys generated on a phone are compared against keys
 * generated on a laptop and by the server, and an algorithm that differs even in
 * rounding puts an author's chapters in a different order on each device.
 * `order.node.test.ts` checks this port against vectors produced by running the Java.
 *
 * Between any two distinct keys there is always another, so inserting or reordering
 * never rewrites siblings — and unlike float-based indexing it never runs out of
 * precision. Arithmetic on these strings is always a bug: they are compared, never
 * computed.
 */

/** Base-62 in ASCII order, so string comparison is digit comparison. */
const DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

export class OrderKeyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "OrderKeyError";
  }
}

function digitAt(value: string, index: number): string {
  return index < value.length ? value[index]! : "0";
}

function suffix(value: string, from: number): string {
  return from < value.length ? value.slice(from) : "";
}

/**
 * Returns a key sorting strictly between `after` and `before`.
 *
 * `after` null or empty means "before everything"; `before` null means "after
 * everything". Throws if the pair is out of order, or if either key ends in '0' —
 * such a key cannot be extended downward, which the algorithm relies on.
 */
export function between(after: string | null, before: string | null): string {
  const a = after ?? "";

  if (before !== null && a >= before) {
    throw new OrderKeyError(`after (${a}) must sort before before (${before})`);
  }
  if (a.endsWith("0") || (before !== null && before.endsWith("0"))) {
    throw new OrderKeyError("order keys must not end in '0'");
  }

  if (before !== null) {
    let common = 0;
    while (common < before.length && digitAt(a, common) === before[common]) common += 1;
    if (common > 0) {
      return before.slice(0, common) + between(suffix(a, common), before.slice(common));
    }
  }

  const digitA = a.length === 0 ? 0 : DIGITS.indexOf(a[0]!);
  const digitB =
    before !== null && before.length > 0 ? DIGITS.indexOf(before[0]!) : DIGITS.length;

  if (digitB - digitA > 1) {
    // Java rounds half away from zero for positives and so does JS for these values;
    // both operands are small non-negative integers, so the two agree exactly.
    const mid = Math.round(0.5 * (digitA + digitB));
    return DIGITS[mid]!;
  }

  // Adjacent digits: there is no room at this position, so descend.
  if (before !== null && before.length > 1) return before.slice(0, 1);
  return DIGITS[digitA]! + between(suffix(a, 1), null);
}

/** The key for the only item in an empty list. */
export function first(): string {
  return between(null, null);
}

/**
 * Keys for `count` new items placed between two existing ones.
 *
 * Generated by walking forward rather than by calling `between` with the same pair
 * repeatedly — that would return the same key every time and collide on the sibling
 * order index.
 */
export function betweenMany(
  after: string | null,
  before: string | null,
  count: number,
): string[] {
  if (count < 0) throw new OrderKeyError(`count must not be negative: ${count}`);
  const keys: string[] = [];
  let cursor = after;
  for (let i = 0; i < count; i += 1) {
    const key = between(cursor, before);
    keys.push(key);
    cursor = key;
  }
  return keys;
}
